import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* root layout used accross the app */}
        <nav className="menu">
          <ul>
            <li><Link href="#Accueil">Accueil</Link></li>
            <li><Link href="/dashboard">dashboard</Link></li>
            <li><Link href="#Contact">Contact</Link></li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
